#+title: My Emacs configuration file
#+PROPERTY: header-args:emacs-lisp :tangle ./init.el :mkdirp yes

* Welcome!
Welcome to my emacs config! this file writes automatically to init.el

* Package Management
** Repositories
Here, we want to setup the package repositories for org-mode, melpa and elpa.
#+begin_src emacs-lisp
(require 'package)

(setq package-archives '(("melpa" . "https://melpa.org/packages/")
                         ("org" . "https://orgmode.org/elpa/")
                         ("elpa" . "https://elpa.gnu.org/packages/")))
;; Refresh
(package-initialize)
(unless package-archive-contents
  (package-refresh-contents))

#+end_src
** Use-package
Use-package is a tool to isolate package configurations and make sure that a package is installed.

#+begin_src emacs-lisp

;; Ensure that use-package is installed
(unless (package-installed-p 'use-package)
  (package-install 'use-package))

(require 'use-package)


(setq use-package-always-ensure t)
#+end_src

* GUI settings
** Toolbar & other ugly stuff
Emacs is ugly by default, these following lines will remove the toolbar, bell, welcome message, scrollbar and tooltips.

#+begin_src emacs-lisp
(setq inhibit-startup-message t)

(scroll-bar-mode -1)        ; Disable visible scrollbar
(tool-bar-mode -1)          ; Disable the toolbar
(tooltip-mode -1)           ; Disable tooltips      

(menu-bar-mode -1)            ; Disable the menu bar

;; Set up the visible bell
(setq visible-bell t)

#+end_src

** Line numbers
This will disable line numbers in certain modes.

#+begin_src emacs-lisp
(column-number-mode)
(global-display-line-numbers-mode t)

;; Disable line numbers for some modes
(dolist (mode '(org-mode-hook
                term-mode-hook
		    helm-mode-hook
                shell-mode-hook
                eshell-mode-hook))
  (add-hook mode (lambda () (display-line-numbers-mode 0))))

#+end_src

** Font
I enjoy a lot Microsoft's Cascadia Code.
#+begin_src emacs-lisp
(set-face-attribute 'default nil :font "Cascadia Code" :height 120)

(set-face-attribute 'fixed-pitch nil :font "Cascadia Code" :height 120)

(add-to-list 'default-frame-alist '(font . "Cascadia Code 12"))

;; Set cursor
(setq-default cursor-type 'bar)
#+end_src

** Dashboard
Dashboard is a replacement for emacs's default launch screen, it is highly customizable.

#+begin_src emacs-lisp
(use-package dashboard
  :ensure t
  :config
  (dashboard-setup-startup-hook))

;; Set the title
(setq dashboard-banner-logo-title "Welcome to Emacs!")

;; Set the banner
(setq dashboard-startup-banner 'logo)

;; Icons
(setq dashboard-set-heading-icons t)
(setq dashboard-set-file-icons t)

;; Navigator
(setq dashboard-set-navigator t)


;; Widgets
(setq dashboard-items '((recents  . 5)))

#+end_src

** Colorscheme
This sets up the =doom-nord= colorscheme.
#+begin_src emacs-lisp
(use-package doom-themes
:init (load-theme 'doom-nord t))
#+end_src

** Modeline
This installs =doom-modeline= which is a customizable bar.

#+begin_src emacs-lisp
;; Icons
(use-package all-the-icons)

(use-package doom-modeline
  :init (doom-modeline-mode 1)
  :custom ((doom-modeline-height 30)))
#+end_src
** Which-key
=which-key= is a tool that shows you every possible completions for keybindings.
#+begin_src emacs-lisp
(use-package which-key
  :defer 0
  :diminish which-key-mode
  :config
  (which-key-mode)
  (setq which-key-idle-delay 1))
#+end_src

* Misc tools
** Helm & Projectile
helm is a completion framework for emacs, projectile is a tool to manage projects.

#+begin_src emacs-lisp
(use-package helm)
(use-package helm-projectile)

(add-to-list 'projectile-globally-ignored-file-suffixes ".o")
(add-to-list 'projectile-globally-ignored-directories "limine")

(setq projectile-indexing-method 'hybrid)
#+end_src

** Autopair
=autopair= pairs brackets automatically.

#+begin_src emacs-lisp
(use-package autopair
  :config (electric-pair-mode))
#+end_src

** Rainbow-delimiters
=rainbow-delimiters= sets the brackets to be colored.

#+begin_src emacs-lisp
(use-package rainbow-delimiters
  :hook ((prog-mode) . 'rainbow-delimiters-mode))
#+end_src
* Development
** C & C++
Adds autocompletion for C & C++.
#+begin_src emacs-lisp
(use-package clang-format)
(setq clang-format-style "file")

;; Auto-completion
(use-package irony
  :hook ((c-mode) . 'irony-mode)
  )

(use-package company
  :config (add-to-list 'company-backends '(company-irony company-irony-c-headers))
  (global-company-mode))

(setq company-backends (delete 'company-semantic company-backends))

(require 'cc-mode)
(define-key c-mode-map  [(tab)] 'company-complete)
(define-key c++-mode-map  [(tab)] 'company-complete)
#+end_src

* Org-mode
** Setup
This sets up org-mode.
#+begin_src emacs-lisp
(defun abx/org-font-setup ()
  ;; Replace list hyphen with dot
  (font-lock-add-keywords 'org-mode
                          '(("^ *\\([-]\\) "
                             (0 (prog1 () (compose-region (match-beginning 1) (match-end 1) "•"))))))
   ;; Set faces for heading levels
  (dolist (face '((org-level-1 . 1.2)
                  (org-level-2 . 1.1)
                  (org-level-3 . 1.05)
                  (org-level-4 . 1.0)
                  (org-level-5 . 1.1)
                  (org-level-6 . 1.1)
                  (org-level-7 . 1.1)
		  (org-level-8 . 1.1)))))

(defun abx/org-mode-setup ()
  (org-indent-mode)
  (visual-line-mode 1))

(use-package org
  :pin org
  :commands (org-capture org-agenda)
  :hook (org-mode .  abx/org-mode-setup)
  :config
  (setq org-ellipsis " ▾")
  (setq org-hide-emphasis-markers t)
  (abx/org-font-setup))

(with-eval-after-load 'org
  (org-babel-do-load-languages
      'org-babel-load-languages
      '((emacs-lisp . t)
      (python . t)))

  (push '("conf-unix" . conf-unix) org-src-lang-modes))

(defun abx/org-babel-tangle-config ()
  (when (string-equal (file-name-directory (buffer-file-name))
                      (expand-file-name user-emacs-directory))
    ;; Dynamic scoping to the rescue
    (let ((org-confirm-babel-evaluate nil))
      (org-babel-tangle))))

(add-hook 'org-mode-hook (lambda () (add-hook 'after-save-hook #'abx/org-babel-tangle-config)))

#+end_src

** Org-bullets

=org-bullets= replaces =*= with custom symbols.

#+begin_src emacs-lisp

(use-package org-bullets
  :hook (org-mode . org-bullets-mode)
  :custom
  (org-bullets-bullet-list '("◉" "○" "●" "○" "●" "○" "●")))

#+end_src

** UI
This sets up padding to make it file more like you're editing a document.

#+begin_src emacs-lisp
  
(defun efs/org-mode-visual-fill ()
  (setq visual-fill-column-width 100
        visual-fill-column-center-text t)
  (visual-fill-column-mode 1))

(use-package visual-fill-column
  :hook (org-mode . efs/org-mode-visual-fill))
#+end_src
* Keybindings
** Evil
This sets up =evil= the Extensible VI Layer
#+begin_src emacs-lisp
(use-package evil)
(evil-mode)
#+end_src

** Keys
These are my kinda crappy keybindings.
#+begin_src emacs-lisp
(global-unset-key (kbd "<left>"))

(global-unset-key (kbd "<right>"))

(global-unset-key (kbd "<up>"))

(global-unset-key (kbd "<down>"))



(global-set-key (kbd "C-S-x") 'kill-whole-line)

(global-set-key (kbd "C-S-c") 'clang-format-buffer)

(global-set-key (kbd "C-x C-f") 'helm-projectile)

(global-set-key (kbd "C-S-f") 'find-file)
(global-set-key (kbd "C-z") 'undo)

(global-set-key (kbd "C-x C-r") 'helm-recentf)

(global-set-key (kbd "C-)") 'compile)

#+end_src
